services:

  app:
    build:
      args:
        - SOURCE_JAR=./target
    volumes:
      - ./config-map/${ENV}/application.properties:/data/application.properties
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DB_HOST=${DATABASE_HOST}
      - DB_PORT=${DATABASE_PORT}
      - DB_USER=${DATABASE_USER}
      - DB_PASS=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
    ports:
      - ${APPLICATION_BE_PORT}:${APPLICATION_BE_PORT}
    env_file:
      - ${PATH_CONNECTION_KEY}/application/.env
